name             'dmi'
maintainer       'Criteo'
maintainer_email 'sre-core-infra@criteo.com'
license          'All rights reserved'
description      'Installs/Configures dmi'
long_description 'Installs/Configures dmi'
issues_url       'https://github.com/criteo-cookbooks/dmi'
source_url       'https://github.com/criteo-cookbooks/dmi'
version          '0.14.0'
supports         'centos'
supports         'debian'
supports         'windows'
depends          'windows'
